defaults: &defaults
  docker:
    - image: debian:jessie

      environment:
        GITHUB_USER: resin-io-playground
        GITHUB_REPO: circle-github-deploy
        BINARY: circle-github-deploy

  steps:
    - checkout

    - run: |
        GIT_TAG=$(git tag -l --points-at HEAD)
        echo "export GIT_TAG=$GIT_TAG" >> $BASH_ENV

    - run: |
        VERSION=$GIT_TAG
        if [ -z "$GIT_TAG" ]; then VERSION="$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)"; fi
        echo "export VERSION=$VERSION" >> $BASH_ENV

    - run: |
        ARCHIVE_NAME="$BINARY-$VERSION-$CIRCLE_JOB.tar.gz"
        echo "export ARCHIVE_NAME=$ARCHIVE_NAME" >> $BASH_ENV
        echo "export ARCHIVE_PATH=/tmp/dist/$ARCHIVE_NAME" >> $BASH_ENV

    - run: mkdir -p /tmp/build /tmp/dist
    - run: dd if=/dev/urandom of=/tmp/build/$TARGET.bin count=1
    - run: tar -czvf $ARCHIVE_PATH -C /tmp/build .

    - store_artifacts:
        path: /tmp/dist
        destination: /

version: 2

jobs:
  aarch64:
    <<: *defaults
    environment:
      TARGET: aarch64-unknown-linux-gnu

  rpi:
    <<: *defaults
    environment:
      TARGET: arm-unknown-linux-gnueabihf

  armv7hf:
    <<: *defaults
    environment:
      TARGET: armv7-unknown-linux-gnueabihf

  i386:
    <<: *defaults
    environment:
      TARGET: i686-unknown-linux-gnu

  amd64:
    <<: *defaults
    environment:
      TARGET: x86_64-unknown-linux-gnu

workflows:
  version: 2
  build:
    jobs:
      - aarch64:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - rpi:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - armv7hf:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - i386:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - amd64:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
